### ISSUE TITLE
Enable AppVeyour Linux builds

### ISSUE THREAD

**Issue by gsomix** [aardvark-platform/aardvark.docs#21]
AppVeyor supports Linux builds, so it might be useful (and also faster than Travis).

https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux

**Comment by haraldsteinlechner** [comment]
oh cool. currently our travis builds not even work at all - some weired
package messup. have ever used appveyer linux? anything to consider?

Evgeniy Andreev <notifications@github.com> schrieb am Mi., 31. Juli 2019,
22:59:
