### ISSUE TITLE
Vanilla dotnet becomes unmanageable with more and more demos..

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.docs#29]
We now have sky and ssao example, both using paket since listing all packages transitively is a nightmare. i'm unaware of a dotnet solution to this.
maybe we should move back to paket for uniformity and clarity. @gsomix as author of vanilla docs - do you have another idea?

**Comment by gsomix** [comment]
Yeah, I think Paket might be more convenient for multi-project repos, especially for examples. So let's go for it. 

It's not related to the issue, but I think that .NET SDK templates should be still vanilla dotnet projects. Let me know if it inconvenient, maybe we can fix it somehow.

Thanks!
